### ISSUE TITLE
Whether to support query conditional filtering？

### ISSUE THREAD

**Issue by kerven88** [LeakIX/estk#1]
Can you support conditional filtering like elasticdump's --searchBody?

--searchBody='
{
"query": {
"range": {
"activity.S_T_VD_EVENTOCCURDATE.raw": {
"gte": "2021-11-18",
"lt": "2021-11-19"
}
}
}
}'

**Comment by gboddin** [comment]
Not a priority atm since you could use the following syntax :

`+activity.S_T_VD_EVENTOCCURDATE.raw:>2021-11-18 +activity.S_T_VD_EVENTOCCURDATE.raw:<2021-11-19`

See https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html
